// xpra packet type names. Mirrors the `PACKET_TYPES` table from the upstream
// xpra-html5 Constants.js — kept here so our client does not depend on the
// vendored Constants module.
export const PKT = {
  control: 'control',
  audio_signal: 'audio-signal',
  bell: 'bell',
  buffer_refresh: 'buffer-refresh',
  button_action: 'button-action',
  challenge: 'challenge',
  clipboard_request: 'clipboard-request',
  clipboard_token: 'clipboard-token',
  clipboard_contents_none: 'clipboard-contents-none',
  clipboard_contents: 'clipboard-contents',
  close: 'close',
  close_window: 'close-window',
  configure_override_redirect: 'configure-override-redirect',
  configure_window: 'configure-window',
  connection_data: 'connection-data',
  cursor: 'cursor',
  damage_sequence: 'damage-sequence',
  desktop_size: 'desktop_size',
  configure_display: 'configure-display',
  disconnect: 'disconnect',
  draw: 'draw',
  encodings: 'encodings',
  eos: 'eos',
  error: 'error',
  focus: 'focus',
  hello: 'hello',
  initiate_moveresize: 'initiate-moveresize',
  key_action: 'key-action',
  keymap_changed: 'keymap-changed',
  keyboard_config: 'keyboard-config',
  lost_window: 'lost-window',
  map_window: 'map-window',
  new_override_redirect: 'new-override-redirect',
  new_window: 'new-window',
  ping: 'ping',
  ping_echo: 'ping_echo',
  pointer_position: 'pointer-position',
  raise_window: 'raise-window',
  set_clipboard_enabled: 'set-clipboard-enabled',
  setting_change: 'setting-change',
  sound_control: 'sound-control',
  sound_data: 'sound-data',
  startup_complete: 'startup-complete',
  suspend: 'suspend',
  resume: 'resume',
  unmap_window: 'unmap-window',
  wheel_motion: 'wheel-motion',
  window_icon: 'window-icon',
  window_metadata: 'window-metadata',
  window_move_resize: 'window-move-resize',
  window_resized: 'window-resized',
} as const